## Homework 1: Introduction to Machine Learning for Machine Learning Zoomcamp 2025

### Q1. Pandas version

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.1'

R1: '2.3.1'

#### Getting Data

In [3]:
# data ='https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'

In [4]:
# !wget $data 

In [5]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [6]:
df.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217

### Q2. Records count

In [7]:
df.shape

(9704, 11)

R2: 9704 

### Q3. Fuel types

In [8]:
df.fuel_type.nunique()

2

In [9]:
df.fuel_type.value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

R3: 2

### Q4. Missing values

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

R4: 4

### Q5. Max fuel efficiency

In [11]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

R5: 23.75

### Q6. Median value of horsepower

In [12]:
median = df.horsepower.median()
median

np.float64(149.0)

In [13]:
mode = df.horsepower.mode()
mode

0    152.0
Name: horsepower, dtype: float64

In [14]:
df["horsepower"] = df["horsepower"].fillna(mode[0])

In [15]:
median = df.horsepower.median()
median

np.float64(152.0)

In [16]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

R6: Yes, it increased

### Q7. Sum of weights

In [17]:
df_asia = df[df.origin == 'Asia']

In [18]:
df_asia.head(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820

In [19]:
df_asia = df_asia [['vehicle_weight','model_year']]

In [20]:
df_asia = df_asia.reset_index(drop=True)

In [21]:
df_asia = df_asia.loc[: 6]

In [22]:
X = df_asia.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [23]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [24]:
XTX = X.T.dot(X)

In [25]:
import numpy as np

In [26]:
XTX_inv = np.linalg.inv(XTX)

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [28]:
Inv_por_T = XTX_inv.dot(X.T)

In [29]:
w = Inv_por_T.dot(y)
w

array([0.01386421, 0.5049067 ])

In [30]:
sum(w)

np.float64(0.5187709081074016)

R7: 0,51